# Site settings
title: OpenProcurement
description: > # this means to ignore newlines until "baseurl:"
  Development of Open Procurement system
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openprcurement.github.io" # the base hostname & protocol for your site
permalink: none

# Languages
languages:
  - name: 'English'
    key: 'en'
  - name: 'Українська'
    key: 'ua'
  - name: 'Русский'
    key: 'ru'

# Build settings
markdown: kramdown

# Prose settings
prose:
  rooturl: '_posts'
